### ISSUE TITLE
runtimelauncher fails with NullPointerException on 7.17.0

### ISSUE THREAD

**Issue by datakurre** [mendix/nixpkgs-mendix#1]
@svanderburg I tried this out with a fresh starter app that was on runtime 7.17.0. Everything worked as expected for build and runtime 7.17.0 up to systemd failed on executing runtimelauncher with the exception below.

runtimelauncher started fine when configured to start as root user, so probably 7.17.0 expected something that was not available for created "mendix" user

```
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:197)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:197)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:31)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$.com$mendix$container$deployment$internal$Interpreters$ClassLoaders$$delete$1(Interpreters.scala:80)
	at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$$anon$1.$anonfun$config$3(Interpreters.scala:93)
	at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$$anon$1.$anonfun$config$3$adapted(Interpreters.scala:93)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$$anon$1.<init>(Interpreters.scala:93)
	at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$.createClassloader(Interpreters.scala:85)
	at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$.$anonfun$newDependency$1(Interpreters.scala:149)
	at cats.data.StateFunctions.$anonfun$modify$4(IndexedStateT.scala:299)
	at cats.data.StateFunctions.$anonfun$apply$1(IndexedStateT.scala:289)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at cats.data.IndexedStateT.$anonfun$run$1(IndexedStateT.scala:66)
	at cats.Eval$.loop$1(Eval.scala:367)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
	at cats.Eval$FlatMap.value(Eval.scala:308)
	at com.mendix.container.deployment.Runners$.runClassloadersHierarchyBuilder(Runners.scala:118)
	at com.mendix.container.componentregistry.internal.ClassloaderComponentReader$.buildHierarchy(ClassloaderComponentReader.scala:207)
	at com.mendix.container.componentregistry.internal.ClassloaderComponentReader$.read(ClassloaderComponentReader.scala:22)
	at com.mendix.container.componentregistry.ComponentRegistry$.run(ComponentRegistry.scala:17)
	at com.mendix.container.boot.Container$.doStart(Container.scala:131)
	at com.mendix.container.boot.Container$.$anonfun$start$3(Container.scala:109)
	at com.mendix.container.boot.Container$.time(Container.scala:181)
	at com.mendix.container.boot.Container$.start(Container.scala:109)
	at com.mendix.container.boot.Main$.$anonfun$new$1(Main.scala:11)
	at scala.util.Either.flatMap(Either.scala:338)
	at com.mendix.container.config.ProjectConfig$.run(ProjectConfig.scala:64)
	at com.mendix.container.boot.Main$.delayedEndpoint$com$mendix$container$boot$Main$1(Main.scala:11)
	at com.mendix.container.boot.Main$delayedInit$body.apply(Main.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.mendix.container.boot.Main$.main(Main.scala:9)
	at com.mendix.container.boot.Main.main(Main.scala)
```

**Comment by datakurre** [comment]
Closing, because not tested on newer versions.
